application: jefallstarbot
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:

- url: /favicon\.ico
  static_files: static/ico/favicon.ico
  upload: favicon\.ico

- url: /js
  static_dir: static/js

- url: /css
  static_dir: static/css

- url: /img
  static_dir: static/img

- url: /.*
  script: main.py

  
libraries:
- name: django
  version: "1.2"
  
env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'
  